# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Pachong standalone executable.

Build:
    pyinstaller pachong.spec --clean

Output:
    dist/pachong.exe          (CLI tool)
    dist/pachong-api.exe      (API server)
    dist/pachong-scheduler.exe (Scheduler)
    dist/pachong-worker.exe   (Worker)
"""

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

a = Analysis(
    ['pachong/cli/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/*.yaml', 'config'),
        ('pachong/storage/postgres/migrations', 'pachong/storage/postgres/migrations'),
    ],
    hiddenimports=[
        'pachong',
        'pachong.core',
        'pachong.core.models',
        'pachong.core.settings',
        'pachong.core.compression',
        'pachong.core.registry',
        'pachong.core.errors',
        'pachong.scheduler',
        'pachong.scheduler.engine',
        'pachong.scheduler.priority',
        'pachong.scheduler.rate_limiter',
        'pachong.scheduler.frontier',
        'pachong.scheduler.deduplication',
        'pachong.scheduler.sitemap',
        'pachong.queue',
        'pachong.queue.kafka',
        'pachong.queue.backpressure',
        'pachong.queue.schemas',
        'pachong.network',
        'pachong.network.session',
        'pachong.network.pool',
        'pachong.network.adaptive',
        'pachong.network.middleware',
        'pachong.network.response',
        'pachong.anti_detect',
        'pachong.anti_detect.identity',
        'pachong.anti_detect.identity.generator',
        'pachong.anti_detect.identity.profile',
        'pachong.anti_detect.identity.store',
        'pachong.anti_detect.fingerprint',
        'pachong.anti_detect.fingerprint.browser',
        'pachong.anti_detect.fingerprint.canvas',
        'pachong.anti_detect.fingerprint.webgl',
        'pachong.anti_detect.fingerprint.audio',
        'pachong.anti_detect.fingerprint.tls',
        'pachong.anti_detect.fingerprint.consistency',
        'pachong.anti_detect.behavior',
        'pachong.anti_detect.behavior.mouse',
        'pachong.anti_detect.behavior.scroll',
        'pachong.anti_detect.behavior.typing',
        'pachong.anti_detect.behavior.conductor',
        'pachong.anti_detect.bandit',
        'pachong.anti_detect.bandit.environment',
        'pachong.anti_detect.bandit.policies',
        'pachong.anti_detect.bandit.feedback',
        'pachong.anti_detect.proxy',
        'pachong.anti_detect.proxy.pool',
        'pachong.anti_detect.proxy.rotator',
        'pachong.anti_detect.proxy.health',
        'pachong.extractor',
        'pachong.extractor.base',
        'pachong.extractor.schema_org',
        'pachong.extractor.css_xpath',
        'pachong.extractor.rule_manager',
        'pachong.extractor.llm_healer',
        'pachong.extractor.adaptive',
        'pachong.extractor.multimodal',
        'pachong.extractor.render',
        'pachong.extractor.pipeline',
        'pachong.storage',
        'pachong.storage.blob',
        'pachong.storage.blob.s3_client',
        'pachong.storage.postgres',
        'pachong.storage.postgres.models',
        'pachong.storage.postgres.engine',
        'pachong.storage.postgres.repository',
        'pachong.storage.mongo',
        'pachong.storage.mongo.client',
        'pachong.storage.mongo.repository',
        'pachong.storage.redis_',
        'pachong.storage.redis_.client',
        'pachong.storage.redis_.ratelimit',
        'pachong.storage.redis_.lock',
        'pachong.resilience',
        'pachong.resilience.metrics',
        'pachong.resilience.collector',
        'pachong.resilience.ban_detector',
        'pachong.resilience.adaptive_throttle',
        'pachong.resilience.circuit_breaker',
        'pachong.tracing',
        'pachong.tracing.setup',
        'pachong.tracing.middleware',
        'pachong.tracing.spans',
        'pachong.tracing.exporters',
        'pachong.serverless',
        'pachong.serverless.base',
        'pachong.serverless.local',
        'pachong.serverless.payload',
        'pachong.serverless.dispatcher',
        'pachong.api',
        'pachong.api.app',
        'pachong.api.routes',
        'pachong.api.routes.tasks',
        'pachong.api.routes.results',
        'pachong.cli',
        'pachong.cli.worker',
        'pachong.cli.scheduler',
        # Third-party
        'aiohttp',
        'aiokafka',
        'asyncpg',
        'motor',
        'redis',
        'pydantic',
        'pydantic_settings',
        'sqlalchemy',
        'structlog',
        'prometheus_client',
        'playwright',
        'typer',
        'fastapi',
        'uvicorn',
        'yaml',
        'brotli',
        'lxml',
        'orjson',
        'tenacity',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Main CLI executable (pachong.exe)
main_exe = EXE(
    a.pure,
    a.zipped_data,
    a.binaries,
    a.datas,
    a.scripts,
    [],
    name='pachong',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # CLI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
